# Generated by Django 2.0.4 on 2018-04-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrauser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='first name'),
        ),
    ]
