# Generated by Django 2.0.4 on 2018-04-12 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0002_auto_20180412_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrauser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
