# Generated by Django 2.0.4 on 2018-04-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0003_terrauser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features', to='terra.Layer'),
        ),
    ]
