# Generated by Django 2.0.4 on 2018-04-24 10:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0004_auto_20180419_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terrauser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='terrauser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='terrauser',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
