# Generated by Django 2.0.5 on 2018-05-18 12:50

from django.db import migrations

import terracommon.terra.fields


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0006_auto_20180518_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='to_date',
        ),
        migrations.AddField(
            model_name='feature',
            name='from_date',
            field=terracommon.terra.fields.DateFieldYearLess(default='01-01', help_text='Layer validity period start'),
        ),
        migrations.AddField(
            model_name='feature',
            name='to_date',
            field=terracommon.terra.fields.DateFieldYearLess(default='12-31', help_text='Layer validity period end'),
        ),
    ]
