# Generated by Django 2.0.5 on 2018-05-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0007_auto_20180518_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='group',
            field=models.CharField(default='__nogroup__', max_length=255),
        ),
    ]
