# Generated by Django 2.0.5 on 2018-05-31 14:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0008_layer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='identifier',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
