# Generated by Django 2.0.6 on 2018-06-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0009_feature_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terrauser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='terrauser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='TerraUser',
        ),
    ]
