# Generated by Django 2.0.9 on 2018-11-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0015_auto_20181005_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='tiles_maxzoom',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='layer',
            name='tiles_minzoom',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
