# Generated by Django 2.0.9 on 2018-11-09 08:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0016_auto_20181108_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='tiles_pixel_buffer',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='layer',
            name='tiles_properties_filter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), null=True, size=None),
        ),
    ]
