# Generated by Django 2.0.13 on 2019-04-25 16:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import terracommon.terra.validators


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0019_merge_20190329_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='type_geom',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('Point', 'Point'), ('MultiPoint', 'Multi Point'), ('LineString', 'Linestring'), ('MultiLineString', 'Multi Linestring'), ('Polygon', 'Polygone'), ('MultiPolygon', 'Multi Polygon'), ('GeometryCollection', 'Geometry Collection')], default='Undefined', max_length=255),
        ),
        migrations.AlterField(
            model_name='layer',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, validators=[terracommon.terra.validators.validate_json_schema]),
        ),
    ]
