# Generated by Django 2.0.13 on 2019-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0022_auto_20190417_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='type_geom',
            field=models.IntegerField(blank=True, choices=[(0, 'Point'), (4, 'MultiPoint'), (1, 'LineString'), (5, 'MultiLineString'), (3, 'Polygon'), (6, 'MultiPolygon'), (7, 'GeometryCollection')], null=True),
        ),
    ]
