# Generated by Django 2.0.13 on 2019-04-01 11:39

try:
    from django.db.models import JSONField
except ImportError:  # TODO Remove when dropping Django releases < 3.1
    from django.contrib.postgres.fields import JSONField
from django.db import migrations
import geostore.validators


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0019_merge_20190329_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['id'], 'permissions': (('can_update_features_properties', 'Is able update geometries properties'), ('can_export_layers', 'Is able to export layers'), ('can_import_layers', 'Is able to import layers'))},
        ),
        migrations.AlterField(
            model_name='layer',
            name='schema',
            field=JSONField(blank=True, default=dict, validators=[geostore.validators.validate_json_schema]),
        ),
    ]
