# Generated by Django 2.0.13 on 2019-05-23 13:28

from django.db import migrations, models
import geostore.models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0023_layer_type_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='geom_type',
            field=models.IntegerField(choices=[(0, geostore.models.GeometryTypes(0)), (1, geostore.models.GeometryTypes(1)), (3, geostore.models.GeometryTypes(3)), (4, geostore.models.GeometryTypes(4)), (5, geostore.models.GeometryTypes(5)), (6, geostore.models.GeometryTypes(6)), (7, geostore.models.GeometryTypes(7))], null=True),
        ),
    ]
