# Generated by Django 2.2.6 on 2019-11-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0033_arrayobjectproperty_layerschemaproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrayobjectproperty',
            name='prop_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean'), ('array_integer', 'Array Integer'), ('array_string', 'Array string'), ('array_number', 'Array number'), ('array_object', 'Array object')], max_length=50),
        ),
        migrations.AlterField(
            model_name='layerschemaproperty',
            name='prop_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean'), ('array_integer', 'Array Integer'), ('array_string', 'Array string'), ('array_number', 'Array number'), ('array_object', 'Array object')], max_length=50),
        ),
    ]
