# Generated by Django 2.2.7 on 2019-11-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0033_featureextrageom_layerextrageom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layerrelation',
            old_name='schema',
            new_name='settings',
        ),
    ]
