# Generated by Django 2.2.8 on 2019-12-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0033_featureextrageom_layerextrageom'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerextrageom',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
