# Generated by Django 2.2.6 on 2019-11-05 10:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0034_auto_20191104_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrayobjectproperty',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Define extra options to json schema property'),
        ),
        migrations.AlterField(
            model_name='layerschemaproperty',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Define extra options to json schema property'),
        ),
    ]
