# Generated by Django 2.2.7 on 2019-11-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0034_auto_20191128_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerrelation',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layerrelation',
            name='slug',
            field=models.SlugField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='layerrelation',
            unique_together={('name', 'origin')},
        ),
    ]
