# Generated by Django 2.2.7 on 2019-11-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0035_auto_20191128_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerrelation',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
