# Generated by Django 2.2.8 on 2020-01-16 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0035_layerextrageom_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='identifier',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
