# Generated by Django 2.2.6 on 2019-11-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0035_auto_20191105_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrayobjectproperty',
            name='array_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean'), ('object', 'Object')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layerschemaproperty',
            name='array_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean'), ('object', 'Object')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arrayobjectproperty',
            name='prop_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean'), ('array', 'Array')], max_length=50),
        ),
        migrations.AlterField(
            model_name='layerschemaproperty',
            name='prop_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean'), ('array', 'Array')], max_length=50),
        ),
    ]
