# Generated by Django 2.2.6 on 2019-11-04 16:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0036_auto_20200116_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerSchemaProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('title', models.CharField(max_length=250)),
                ('prop_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean'), ('array', 'Array')], max_length=50)),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Define extra options to json schema property')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_properties', to='geostore.Layer')),
                ('array_type', models.CharField(blank=True, choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean'), ('object', 'Object')], max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Schema property',
                'verbose_name_plural': 'Schema properties',
            },
        ),
        migrations.CreateModel(
            name='ArrayObjectProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('title', models.CharField(max_length=250)),
                ('prop_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean'), ('array', 'Array')], max_length=50)),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Define extra options to json schema property')),
                ('array_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='array_properties', to='geostore.LayerSchemaProperty')),
                ('array_type', models.CharField(blank=True, choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean')], max_length=50)),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Array object schema property',
                'verbose_name_plural': 'Array object schema properties',
            },
        ),
    ]
