# Generated by Django 2.2.6 on 2019-11-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0036_auto_20191105_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrayobjectproperty',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layerschemaproperty',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arrayobjectproperty',
            name='array_type',
            field=models.CharField(blank=True, choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean'), ('object', 'Object')], max_length=50),
        ),
        migrations.AlterField(
            model_name='layerschemaproperty',
            name='array_type',
            field=models.CharField(blank=True, choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean'), ('object', 'Object')], max_length=50),
        ),
    ]
