# Generated by Django 2.2.7 on 2019-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0036_layerrelation_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerrelation',
            name='multiple',
            field=models.BooleanField(default=True),
        ),
    ]
