# Generated by Django 3.0 on 2019-12-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0035_layerextrageom_editable'),
        ('geostore', '0037_auto_20191105_1116'),
    ]

    operations = [
    ]
