# Generated by Django 2.2.7 on 2019-11-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0038_layerrelation_relation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerrelation',
            name='relation_type',
            field=models.CharField(choices=[(None, 'Manuelle'), ('intersects', 'Intersects'), ('distance', 'Distance')], default=(None, 'Manuelle'), max_length=25),
        ),
    ]
