# Generated by Django 3.0 on 2019-12-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0039_auto_20191128_1224'),
        ('geostore', '0035_layerextrageom_editable'),
    ]

    operations = [
    ]
