# Generated by Django 3.0.2 on 2020-01-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0036_auto_20200116_0926'),
        ('geostore', '0039_remove_layer_schema'),
    ]

    operations = [
    ]
