# Generated by Django 2.2.9 on 2020-01-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0040_merge_20200120_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrayobjectproperty',
            name='array_type',
            field=models.CharField(blank=True, choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('boolean', 'Boolean')], max_length=50),
        ),
        migrations.AlterField(
            model_name='arrayobjectproperty',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='layerschemaproperty',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
