# Generated by Django 3.0.2 on 2020-01-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0041_auto_20200128_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerschemaproperty',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
