# Generated by Django 3.0 on 2019-12-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0041_auto_20191213_1255'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(geom__isvalid=True), name='geom_is_valid'),
        ),
    ]
