# Generated by Django 3.0 on 2019-12-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0042_auto_20191217_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerrelation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[(None, 'Manuelle'), ('intersects', 'Intersects'), ('distance', 'Distance')], default=(None, 'Manuelle'), max_length=25),
        ),
    ]
