# Generated by Django 3.0.1 on 2019-12-19 16:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0043_auto_20191218_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerrelation',
            name='editable',
        ),
        migrations.RemoveField(
            model_name='layerrelation',
            name='multiple',
        ),
        migrations.AddField(
            model_name='layerrelation',
            name='exclude',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
