# Generated by Django 3.0.1 on 2019-12-20 11:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0044_auto_20191219_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerrelation',
            name='exclude',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='qs exclude (ex: {"pk__in": [...], "identifier__in":[...]}'),
        ),
    ]
