# Generated by Django 5.0.1 on 2024-01-12 11:26

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0047_alter_feature_properties'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feature',
            name='geostore_fe_layer_i_c3168f_gist',
        ),
        migrations.RemoveIndex(
            model_name='featureextrageom',
            name='feg_geom_gist_index',
        ),
        migrations.AddIndex(
            model_name='feature',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='geostore_fe_geom_cff9a1_gist'),
        ),
        migrations.AddIndex(
            model_name='featureextrageom',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='feg_geom_gist_index'),
        ),
    ]
