# Generated by Django 5.0.1 on 2024-01-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0048_remove_feature_geostore_fe_layer_i_c3168f_gist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='geom_type',
            field=models.IntegerField(choices=[(0, 'Point'), (1, 'Linestring'), (3, 'Polygon'), (4, 'Multipoint'), (5, 'Multilinestring'), (6, 'Multipolygon'), (7, 'Geometrycollection')], null=True),
        ),
        migrations.AlterField(
            model_name='layerextrageom',
            name='geom_type',
            field=models.IntegerField(choices=[(0, 'Point'), (1, 'Linestring'), (3, 'Polygon'), (4, 'Multipoint'), (5, 'Multilinestring'), (6, 'Multipolygon'), (7, 'Geometrycollection')], null=True),
        ),
    ]
